version: '2'
services:

    php7:
        build: ./docker/php7
        container_name: php7.1_cache_example

        volumes_from:
          - data 

    nginx:
        image: nginx:1.11
        container_name: nginx_cache_example
        ports:
          - 8000:8000
          - 8001:8001

        links:
          - php7

        volumes:
          - ./conf/nginx.conf:/etc/nginx/nginx.conf:ro

        volumes_from:
          - data


    data:
        image: busybox:latest

        volumes:
          - ./cache-example:/srv